title: Android tips
email: peter.laurence@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My experience shares with Android.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  peterLaurence
theme: jekyll-theme-cayman
